tasks: 
  - init: ls -al

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-boot-dev-pack
    - jawandarajbir.react-vscode-extension-pack
    - xabikos.javascriptsnippets